config/routes.rb
Rails.application.routes.draw do
  root 'collections#index'
  
  devise_for :users
  
  resources :collections

  resources :authors, only: [:create, :destroy]

  resources :books, only: [:edit, :update, :create, :destroy]

end

app/models/author.rb
class Author < ActiveRecord::Base
	belongs_to :book
	belongs_to :collection

	validates :name, length: {minimum: 4}

	after_save :save_books

	def save_books
		@author = self[:id]
		# Goodreads API key: need to hide this later
		@key = 'JBdCSEmPL5uPlM3IYj4lw'
		# Name of Author for books query
		@name = self.name.gsub(' ', '%20')
 		@request = "https://www.goodreads.com/search.xml?format=json&key=#{@key}&q=#{@name}"
		@response = HTTParty.get "#{@request}"
		# Array of books from API call
		@book_array = @response['GoodreadsResponse']['search']['results']['work']
		@book_array.each do |book|
			# Book title
			@book_title = book['best_book']['title']
			# Year book was published
			@book_year = book['original_publication_year'].to_s
			# Initialize status with 'not read'
			@book_status = 'not read'
			# Instantiate book
			@book = Book.create(title: @book_title, date: @book_year, status: @book_status, author_id: @author)
		end
	end

	def self.find_book(author)
		@books = author.books
		# sorts books by date
		@books = @books.sort_by {|book|	book.date}
		@flag = 'start'
		# Finds the next book that has not been started or read
		@books.each do |book|
			if book.status == 'not read' && @flag == 'start'
				@flag = 'finish'
				@next_book = book
			end
		end
		@next_book
	end

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :authors
  has_many :collections, through: :books

	validates :title, length: {minimum: 4}
  validates :date, length: {minimum: 4}  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
	belongs_to :user
  has_many :authors
	has_many :books, through: :authors

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many :collections
  # has_many :authors, through: :collections
  # has_many :books, through: :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]

	def new
		@author = Author.new
	end

	def create
		# @collection = Collection.find(params[:collection_id])
		# @author = @collection.authors.create(author_params)

		@author = Author.new(author_params)
	  redirect_to collection_path(@collection)
	end

	def destroy
		@collection = Collection.find(params[:collection_id])
		@author = @collection.authors.find(params[:id])
		@author.destroy
		redirect_to collection_path(@collection)
	end

	private

	def author_params
		params.require(:author).permit(:name) 
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def edit
		@collection = Collection.find(params[:collection_id])
		@author = Author.find(params[:author_id])		
		@book = Book.find(params[:id])
	end

	def update
		@collection = Collection.find(params[:collection_id])
		@author = Author.find(params[:author_id])	
 	  @book = Book.find(params[:id])
		@book.update(status: params[:status])
		redirect_to collection_path(@collection)
	end


	def create
		@author = Author.find(params[:author_id])
		@book = @author.books.create(book_params)
		redirect_to author_path(@author)
	end

	def destroy
		@author = Author.find(params[:author_id])
		@book = @author.books.find(params[:id])
		@book.destroy
		redirect_to author_path(@author)
	end

	private

	def book_params
		params.require(:book).permit(:title, :date, :status) 
	end

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

	before_action :authenticate_user!, except: [:show, :index]

	def index
		@collections = Collection.all
	end

	def new
		@collection = Collection.new
	end

	def show
		@collection = Collection.find(params[:id])
	end

	def edit
		@collection = Collection.find(params[:id])
	end

	def create
		@collection = Collection.new(collection_params.merge(user_id: current_user.id))
		if @collection.save
			redirect_to @collection
		else
			render :new
		end
	end

	def update
		@collection = Collection.find(params[:id])
		if @collection.update(collection_params)
			redirect_to @collection
		else
			render :edit
		end
	end

	def destroy
		@collection = Collection.find(params[:id])
		@collection.destroy
		redirect_to collections_url
	end

	private

	def collection_params
		params.require(:collection).permit(:name)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_author.html.erb
<div class='collections'>
	<div class='author_form screen2'>

		<!-- Shows each Author in the Collection -->
		<p>Author's Name: </p>
		<h3><%= author.name %></h3> 
		<p>  <%= link_to 'Remove Author from Collection', [author.collection, author],
		               method: :delete,
		               data: { confirm: 'Are you sure?' } %>
		</p>
		<div class='recommend'>
			<h3>This author's next book:</h3>

			<!-- The find_book method makes Book recommendation based upon earliest date with proper status  -->
			<h4><%= Author.find_book(author).title %></h4>
		</div>
	</div>
	
	<div class='books sec' class='screen'>
		<h4>Books by this Author:</h4>

		<table>
		  <tr>
		  	<!-- Table headers -->
		    <th class='title'>Title</th>
		    <th class='date'>Date</th>
		    <th class='status'>Status</th>
		    <th></th>
		  </tr>	
		  <!-- Sort books by date -->
		  <% @books = author.books.sort_by {|book| book.date} %>
			<% @books.each do |book| %>
				<tr>
					<!-- Listing of each book in table -->
		      <td class='title'><%= book.title %></td>
					<td class='date'><%= book.date %></td>
					<td class= 'status'><%= book.status %></td>
					<td class='link'><%= link_to 'Status', edit_collection_author_book_path(@collection, author, book) %></td>
				  </tr>
		  <% end %>
		</table>
		<p></p>
		<p>** Book data provided by BookReads API **</p>
		<div class='break2'></div>
	</div>	
	<div class='advert'>
		<div class='advertisement2'></div>
	</div>
	<div class='advert'>
		<div class='break'></div>
	</div>
	<div class='advert'>
		<div class='advertisement'></div>
	</div>
</div>

app/views/authors/_form.html.erb
<div class='collection_form sec screen2'>
	<div>
	  <!-- Appears at the bottom of the individual Collection listing showing Authors and Books -->
	  <p>Add an Author to this Collection</p>
		<%= form_for([@collection, @collection.authors.build]) do |f| %>
			<p>
				<%= f.label :name %><br>
				<%= f.text_field :name %>
			</p>
			<p class='actions'>
				<%= f.submit "Add Author to Collection"%>
			</p>
		<% end %>	
	</div>
</div>

app/views/authors/views_not_used/edit.html.erb
<div>
	<h3>Editing author???</h3>
		<%= render 'form' %>
		<%= link_to 'Show', @author %>
		<%= link_to 'Back', authors_path %>
</div>

app/views/authors/views_not_used/show.html.erb
<div>
	<h4>Here is your author</h4>

	???????

	
	<h2><%= @author.name %></h2>
	<%= link_to 'Edit', edit_author_path(@author) %>
	<%= link_to 'Delete', @author, method: :delete %>


</div>

app/views/books/_form.html.erb
<!-- Form to edit the Status of a Book -->
<div>
	<p><%= @book.title %></p>
	<p>Year: <%= @book.date %></p>
	<p>Status: <%= @book.status %></p>
	<%= form_for [@collection, @author, @book] do |f| %>
		<p><%= radio_button_tag(:status, "read") %>
		<%= label_tag(:status_read, "I have Read this book") %></p>
		<p><%= radio_button_tag(:status, "not read") %>
		<%= label_tag(:status_not_read, "I have not Read this book") %></p>
		<p><%= radio_button_tag(:status, "skip") %>
		<%= label_tag(:status_skip, "I will skip this book") %></p>
		<p class='actions'>
			<%= f.submit 'Submit Status' %>
		</p>
	<% end %>	
</div>

app/views/books/edit.html.erb
<div class='book_edit sec'>
  <!-- Change the status of a Book -->
	<p>Edit Book Status</p>
    <ul>
      <li>
		    
        <%= render 'form' %>

      </li>
    </ul> 
</div>

app/views/collections/_form.html.erb
<div class='collection_edit'>
	<!-- Displays errors in creating Collection -->
	<%= form_for(@collection) do |f| %>
		<% if @collection.errors.any? %>
			<div id='error_explanation'>

				<h2><%= pluralize(@collection.errors.count, 'error') %> prohibited this collection from being saved:</h2>

				<ul>
					<% @collection.errors.full_messages.each do |message| %>
						<li><%= message %></li>
					<% end %>
				</ul>

			</div>
		<% end %>

		<!-- Displays input field for Collection -->
		<div class='field'>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</div>
		<p></p>
		<div class='actions'>
			<%= f.submit "Create New Collection" %>
		</div>
	<% end %>
</div>	

app/views/collections/edit.html.erb
<div class='collect_list sec'>
	<p>Editing Collection</p>
    <ul>
      <li>

    		<%= render 'form' %>
        
    		<%= link_to 'Show', @collection %>
    		<%= link_to 'Back', collections_path %>
      </li>
    </ul> 
</div>

app/views/collections/index.html.erb
<div class='collect_list sec'>
  <!-- Displays a list of Collection names -->
	<p>Collections:</p>
		<% @collections.each do |c| %>
			<ul>
				<li><%= c.name  %>
        <!-- Followed by links -->
        <br>
				<%= link_to 'View', collection_path(c)  %>

        <%= link_to 'Edit', edit_collection_path(c) %>

        <%= link_to 'Delete', collection_path(c), method: :delete %></li>
			</ul>
		<% end %>
</div>

app/views/collections/new.html.erb
<div class='collect_list sec'>
	<p>New Collection</p>
	<%= render 'form' %>
	<% link_to 'Back', collections_path %>
</div>

app/views/collections/show.html.erb
<div class='authors sec'>
	<div>

		<!-- Shows name of this Collection -->
		<p class='heading'>Collection: <%= @collection.name %></p>

		<!-- Shows Authors in this Collection which then lists the books -->
		<%= render @collection.authors %>	

		<!-- At bottom of page, form allows you to add an Author to the collection -->
		<%= render 'authors/form' %></li>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NextBooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h1>NextBooks</h1>
		<h4>The app that tells you the Next Books you should read</h4>
	</header>
	<section>

		<article id='top_menu'>
			<div id='notice'>
				<p class="notice"><%= notice %></p>
		  	<p class="alert"><%= alert %></p>
		  </div>
			<nav class='pri' id='sign'>
				<ul>
					<% if user_signed_in? %>
						<li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
					<% else %>
						<li><%= link_to("Sign in", new_user_session_path) %></li>
						<li><%= link_to('Sign up', new_user_registration_path) %></li>
					<% end %>
				</ul>
			</nav>
		</article>
		<div id='wrapper'>
			<div class='pri' id='collect_nav'>
				<ul>
					<li><%= link_to 'Collections', collections_path  %></li>
					<li><%= link_to 'Create a Collection', new_collection_path %></li>
				</ul>
			</div>
		</div> 

		<%= yield %>
				
	</section>
	<footer>Brought to you by a Web Developer who reads
	</footer>
</body>
</html>